apiVersion: networking.k8s.io/v1beta1 
 kind: ingress
 metadata:
   name: myapp
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: openfaas-figlet.local
     http:
       paths:
       - path: /
         backend:
           serviceName: myapp
           servicePort: 8080
